package com.example.demo.formation.projetrh.entities;
// Generated 29 avr. 2021 � 14:35:25 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Absence generated by hbm2java
 */
@Entity
@Table(name = "ABSENCE", schema = "PROJETRH")
public class Absence implements java.io.Serializable {

	private BigDecimal idabsence;
	private Employeweb employeweb;
	private BigDecimal nbjours;
	private String motif;
	private String justicatif;

	public Absence() {
	}

	public Absence(BigDecimal idabsence, Employeweb employeweb) {
		this.idabsence = idabsence;
		this.employeweb = employeweb;
	}

	public Absence(BigDecimal idabsence, Employeweb employeweb, BigDecimal nbjours, String motif, String justicatif) {
		this.idabsence = idabsence;
		this.employeweb = employeweb;
		this.nbjours = nbjours;
		this.motif = motif;
		this.justicatif = justicatif;
	}

	@Id

	@Column(name = "IDABSENCE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdabsence() {
		return this.idabsence;
	}

	public void setIdabsence(BigDecimal idabsence) {
		this.idabsence = idabsence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_EMP", nullable = false)
	public Employeweb getEmployeweb() {
		return this.employeweb;
	}

	public void setEmployeweb(Employeweb employeweb) {
		this.employeweb = employeweb;
	}

	@Column(name = "NBJOURS", precision = 22, scale = 0)
	public BigDecimal getNbjours() {
		return this.nbjours;
	}

	public void setNbjours(BigDecimal nbjours) {
		this.nbjours = nbjours;
	}

	@Column(name = "MOTIF", length = 50)
	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	@Column(name = "JUSTICATIF", length = 20)
	public String getJusticatif() {
		return this.justicatif;
	}

	public void setJusticatif(String justicatif) {
		this.justicatif = justicatif;
	}

}
