package com.example.demo.formation.projetrh.entities;
// Generated 29 avr. 2021 � 14:35:25 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employeweb generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEWEB", schema = "PROJETRH")
public class Employeweb implements java.io.Serializable {

	private BigDecimal code;
	private BigDecimal salaire;
	private String numtel;
	private String nom;
	private String prenom;
	private String adresse;
	private Set<Conges> congeses = new HashSet<Conges>(0);
	private Set<Sanction> sanctions = new HashSet<Sanction>(0);
	private Set<Absence> absences = new HashSet<Absence>(0);

	public Employeweb() {
	}

	public Employeweb(BigDecimal code) {
		this.code = code;
	}

	public Employeweb(BigDecimal code, BigDecimal salaire, String numtel, String nom, String prenom, String adresse,
			Set<Conges> congeses, Set<Sanction> sanctions, Set<Absence> absences) {
		this.code = code;
		this.salaire = salaire;
		this.numtel = numtel;
		this.nom = nom;
		this.prenom = prenom;
		this.adresse = adresse;
		this.congeses = congeses;
		this.sanctions = sanctions;
		this.absences = absences;
	}

	@Id

	@Column(name = "CODE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCode() {
		return this.code;
	}

	public void setCode(BigDecimal code) {
		this.code = code;
	}

	@Column(name = "SALAIRE", precision = 22, scale = 0)
	public BigDecimal getSalaire() {
		return this.salaire;
	}

	public void setSalaire(BigDecimal salaire) {
		this.salaire = salaire;
	}

	@Column(name = "NUMTEL", length = 20)
	public String getNumtel() {
		return this.numtel;
	}

	public void setNumtel(String numtel) {
		this.numtel = numtel;
	}

	@Column(name = "NOM", length = 40)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "ADRESSE", length = 50)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeweb")
	public Set<Conges> getCongeses() {
		return this.congeses;
	}

	public void setCongeses(Set<Conges> congeses) {
		this.congeses = congeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeweb")
	public Set<Sanction> getSanctions() {
		return this.sanctions;
	}

	public void setSanctions(Set<Sanction> sanctions) {
		this.sanctions = sanctions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeweb")
	public Set<Absence> getAbsences() {
		return this.absences;
	}

	public void setAbsences(Set<Absence> absences) {
		this.absences = absences;
	}

}
