package com.example.demo.formation.projetrh.entities;
// Generated 29 avr. 2021 � 14:35:25 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sanction generated by hbm2java
 */
@Entity
@Table(name = "SANCTION", schema = "PROJETRH")
public class Sanction implements java.io.Serializable {

	private BigDecimal refSanction;
	private Employeweb employeweb;
	private String description;
	private String typeSanction;

	public Sanction() {
	}

	public Sanction(BigDecimal refSanction) {
		this.refSanction = refSanction;
	}

	public Sanction(BigDecimal refSanction, Employeweb employeweb, String description, String typeSanction) {
		this.refSanction = refSanction;
		this.employeweb = employeweb;
		this.description = description;
		this.typeSanction = typeSanction;
	}

	@Id

	@Column(name = "REF_SANCTION", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRefSanction() {
		return this.refSanction;
	}

	public void setRefSanction(BigDecimal refSanction) {
		this.refSanction = refSanction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_EMP")
	public Employeweb getEmployeweb() {
		return this.employeweb;
	}

	public void setEmployeweb(Employeweb employeweb) {
		this.employeweb = employeweb;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "TYPE_SANCTION", length = 20)
	public String getTypeSanction() {
		return this.typeSanction;
	}

	public void setTypeSanction(String typeSanction) {
		this.typeSanction = typeSanction;
	}

}
